version: "3.9"

services:
  ui:
    build: ./ui
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
    healthcheck:
      test: curl --fail -s http://localhost/ || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
  api:
    image: ghcr.io/piekstra/tplinkcloud-service:v1.0.0
    restart: always
    healthcheck:
      # slightly confusing, but the container name is the hostname
      # so we have api twice
      test: curl --fail -s http://api/api/v1/time || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
