# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Package React

on:
  push:
    branches:
    - main
    paths:
    - 'ui/**'
    - '!**.md'
  pull_request:
    paths:
    - 'ui/**'
    - '!**.md'

defaults:
  run:
    working-directory: ./ui

jobs:

  build-react:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    env:
      CI: true

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install app dependencies
      run: yarn install
    - name: Build the app
      run: yarn build
    - name: Run tests with coverage
      run: yarn test -- --coverage
